// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const CButton: typeof import("@casual-ui/svelte")["CButton"]
    const CInput: typeof import("@casual-ui/svelte")["CInput"]
    const CLoading: typeof import("@casual-ui/svelte")["CLoading"]
    const CLoadingAudio: typeof import("@casual-ui/svelte")["CLoadingAudio"]
    const CLoadingBar: typeof import("@casual-ui/svelte")["CLoadingBar"]
    const CLoadingBars: typeof import("@casual-ui/svelte")["CLoadingBars"]
    const CLoadingCircleBars: typeof import("@casual-ui/svelte")["CLoadingCircleBars"]
    const CLoadingClock: typeof import("@casual-ui/svelte")["CLoadingClock"]
    const CLoadingComment: typeof import("@casual-ui/svelte")["CLoadingComment"]
    const CLoadingCube: typeof import("@casual-ui/svelte")["CLoadingCube"]
    const CLoadingDot: typeof import("@casual-ui/svelte")["CLoadingDot"]
    const CLoadingDots: typeof import("@casual-ui/svelte")["CLoadingDots"]
    const CLoadingGear: typeof import("@casual-ui/svelte")["CLoadingGear"]
    const CLoadingHeart: typeof import("@casual-ui/svelte")["CLoadingHeart"]
    const CLoadingInfinity: typeof import("@casual-ui/svelte")["CLoadingInfinity"]
    const CLoadingLattice: typeof import("@casual-ui/svelte")["CLoadingLattice"]
    const CLoadingOrbit: typeof import("@casual-ui/svelte")["CLoadingOrbit"]
    const CLoadingOval: typeof import("@casual-ui/svelte")["CLoadingOval"]
    const CLoadingPie: typeof import("@casual-ui/svelte")["CLoadingPie"]
    const CLoadingPuff: typeof import("@casual-ui/svelte")["CLoadingPuff"]
    const CLoadingRings: typeof import("@casual-ui/svelte")["CLoadingRings"]
    const CLoadingSpinBox: typeof import("@casual-ui/svelte")["CLoadingSpinBox"]
    const CLoadingTail: typeof import("@casual-ui/svelte")["CLoadingTail"]
    const CLoadingWifi: typeof import("@casual-ui/svelte")["CLoadingWifi"]
    const CSelect: typeof import("@casual-ui/svelte")["CSelect"]
    const CTag: typeof import("@casual-ui/svelte")["CTag"]
    const openNotification: typeof import("@casual-ui/svelte")["openNotification"]
}

export {}
