name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches-ignore:
      - changeset-release/main
jobs:
  linter:
    name: Running lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with: 
          version: 7.14.0
      - name: Install Dependencies
        run: pnpm i
      - name: ESLint check
        run: pnpm lint
      - name: Prettier check
        run: pnpm format

          
        
